ALTER TABLE "RadarSettings" ADD COLUMN IF NOT EXISTS "radarCronEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "RadarSettings" ADD COLUMN IF NOT EXISTS "emailSendCronEnabled" BOOLEAN NOT NULL DEFAULT false;
