-- AlterTable
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "linkedinUrl" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "discoverySources" TEXT[] DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "RadarSettings" ADD COLUMN IF NOT EXISTS "sourcePlaces" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "RadarSettings" ADD COLUMN IF NOT EXISTS "sourceWeb" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "RadarSettings" ADD COLUMN IF NOT EXISTS "sourceLinkedin" BOOLEAN NOT NULL DEFAULT true;
